### ISSUE TITLE
repl-driven development?

### ISSUE THREAD

**Issue by dwoodlock** [Nappa9693/elfenben#4]
I love the idea of this project btw - I've been struggling with the ClojureScript ecosystem (build, interop with Javascript npm modules) and something simpler and more nodejs focused is right up my alley.  

Is there a way to load a file into the repl? This would allow you to use existing vars (e.g. functions) and iteratively build new functions in the repl as many functional people do.  

Or another version of that - there a way to require a module into the repl?  This would facilitate the same (If I exported everything I needed).  I couldn't find it in the documentation so I assume no.

**Comment by Nappa9693** [comment]
At the moment there is no way to require a module into the REPL. This is due to limitations within the Node  vm module itself which is used to execute the code in the REPL. However I could add functionality to the repl to be able to load a file although it would be bound by the same rules (no require statements).

**Comment by dwoodlock** [comment]
Ah.  That wouldn't be so useful as most of my code is dependent on 3rd party javascript libraries so I wouldn't be able to develop in the repl with some require statements.  Thanks anyway.
